name: Test and Build Kibana Reports

on: [pull_request, push]

env:
  PLUGIN_NAME: opendistroReportsKibana
  OD_VERSION: 1.12.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v1

      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: elastic/kibana
          ref: v7.10.0
          path: kibana-reports/kibana

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.22.1"

      - name: Move Kibana Reports to Plugins Dir
        run: mv kibana-reports kibana/plugins/${{ env.PLUGIN_NAME }}

      - name: Add Chromium Binary to Reporting for Testing
        run: |
          sudo apt install -y libnss3-dev fonts-liberation libfontconfig1
          cd kibana/plugins/${{ env.PLUGIN_NAME }}
          wget https://github.com/opendistro-for-elasticsearch/kibana-reports/releases/download/chromium-1.12.0.0/chromium-linux-x64.zip
          unzip chromium-linux-x64.zip
          rm chromium-linux-x64.zip

      - name: Kibana Plugin Bootstrap
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: cd kibana/plugins/${{ env.PLUGIN_NAME }}; yarn kbn bootstrap

      - name: Test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: cd kibana/plugins/${{ env.PLUGIN_NAME }}; yarn test

      - name: Build Artifact
        run: |
          cd kibana/plugins/${{ env.PLUGIN_NAME }}
          yarn build

          cd build
          mkdir -p ./{linux-x64,linux-arm64,windows-x64}/kibana/${{ env.PLUGIN_NAME }}
          cp ./${{ env.PLUGIN_NAME }}-*.zip ./linux-x64/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-linux-x64.zip
          cp ./${{ env.PLUGIN_NAME }}-*.zip ./linux-arm64/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-linux-arm64.zip
          mv ./${{ env.PLUGIN_NAME }}-*.zip ./windows-x64/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-windows-x64.zip

          cd linux-x64
          wget https://github.com/opendistro-for-elasticsearch/kibana-reports/releases/download/chromium-1.12.0.0/chromium-linux-x64.zip
          unzip chromium-linux-x64.zip -d ./kibana/${{ env.PLUGIN_NAME }}
          zip -ur ./${{ env.PLUGIN_NAME }}-*.zip ./kibana
          mv ./${{ env.PLUGIN_NAME }}-*.zip ..
          cd ..

          cd linux-arm64
          wget https://github.com/opendistro-for-elasticsearch/kibana-reports/releases/download/chromium-1.12.0.0/chromium-linux-arm64.zip
          unzip chromium-linux-arm64.zip -d ./kibana/${{ env.PLUGIN_NAME }}
          zip -ur ./${{ env.PLUGIN_NAME }}-*.zip ./kibana
          mv ./${{ env.PLUGIN_NAME }}-*.zip ..
          cd ..

          cd windows-x64
          wget https://github.com/opendistro-for-elasticsearch/kibana-reports/releases/download/chromium-1.12.0.0/chromium-windows-x64.zip
          unzip chromium-windows-x64.zip -d ./kibana/${{ env.PLUGIN_NAME }}
          zip -ur ./${{ env.PLUGIN_NAME }}-*.zip ./kibana
          mv ./${{ env.PLUGIN_NAME }}-*.zip ..
          cd ..

      - name: Upload Artifact For Linux x64
        uses: actions/upload-artifact@v1
        with:
          name: kibana-reports-linux-x64
          path: kibana/plugins/${{ env.PLUGIN_NAME }}/build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-linux-x64.zip

      - name: Upload Artifact For Linux arm64
        uses: actions/upload-artifact@v1
        with:
          name: kibana-reports-linux-arm64
          path: kibana/plugins/${{ env.PLUGIN_NAME }}/build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-linux-arm64.zip

      - name: Upload Artifact For Windows
        uses: actions/upload-artifact@v1
        with:
          name: kibana-reports-windows-x64
          path: kibana/plugins/${{ env.PLUGIN_NAME }}/build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-windows-x64.zip
